paratestphp/paratest

src/ParaTest/Logging/JUnit/Reader.php, src/ParaTest/Parser/ParsedClass.php, src/ParaTest/Runners/PHPUnit/ResultPrinter.php, test/fixtures/results/empty-test-suite.xml, test/unit/ParaTest/Parser/ParsedClassTest.php, test/unit/ParaTest/Runners/PHPUnit/ResultPrinterTest.php
The reason the previous pull request (https://github.com/brianium/paratest/pull/133) was failing is because when the tests are run with multiple, comma separated groups, the framework would pull all tests to execute. This leaves an empty log file, which is the symptom I was using to diagnose the issue.
The newest change updates the command to get test methods to iterate over comma separated values passed into the annotations.
=> Error message when empty

src/ParaTest/Console/Testers/PHPUnit.php, src/ParaTest/Runners/PHPUnit/Configuration.php, src/ParaTest/Runners/PHPUnit/Options.php, src/ParaTest/Runners/PHPUnit/SuiteLoader.php, test/fixtures/phpunit-file.xml, test/fixtures/phpunit-files-dirs-mix-duplicates.xml, test/fixtures/phpunit-files-dirs-mix.xml, test/fixtures/phpunit-multifile.xml, test/unit/ParaTest/Console/Commands/ParaTestCommandTest.php, test/unit/ParaTest/Console/Testers/PHPUnitTest.php, test/unit/ParaTest/Runners/PHPUnit/SuiteLoaderTest.php
make it possible to spedify a testsuite within phpunit.xml with <file> attributes and execute the specified <file>'s in parallel
=> add support for testsuite parameter (#142)

src/ParaTest/Console/Testers/PHPUnit.php, src/ParaTest/Runners/PHPUnit/Runner.php, test/fixtures/paratest-only-tests/EnvironmentTest.php, test/functional/EmptyRunnerStub.php, test/functional/FunctionalTestBase.php, test/functional/PHPUnitTest.php, test/functional/ParaTestInvoker.php, test/functional/ProcessCallback.php
This pull requests allows the developer to use a custom runner that extends BaseRunner
For me this is a semi-workaround for the windows wrapperrunner problem, because I can provide my own runner with pre-post scripts per token. but i will have a closer look into the windows issues when there is time
also change the tokens from numeric to uniqueid's because that is more generic and you can e.g. do something like creating a prepared database for every token before running the actual test (this custom runner is not included)
=> Allow custom runners

src/ParaTest/Console/Testers/PHPUnit.php, src/ParaTest/Runners/PHPUnit/Configuration.php, src/ParaTest/Runners/PHPUnit/Runner.php, src/ParaTest/Runners/PHPUnit/SuiteLoader.php, test/fixtures/paratest-only-tests/EnvironmentTest.php, test/fixtures/phpunit-files-dirs-mix-nested.xml, test/functional/EmptyRunnerStub.php, test/functional/FunctionalTestBase.php, test/functional/PHPUnitTest.php, test/functional/ParaTestInvoker.php, test/functional/ProcessCallback.php, test/unit/ParaTest/Runners/PHPUnit/SuiteLoaderTest.php
For better structure in phpunit.xml I added the possibility to use nested <testsuite> elements.
for example this is helpful in such a case:
```xml
<testsuites>
<testsuite name="feature 1">
<directory>some-dir</directory>
</testsuite>
<testsuite name="feature 2">
<file>feature2-1Test.php</file>
<file>feature2-2Test.php</file>
</testsuite>
<testsuite name="all">
<testsuite>feature 1</testsuite>
<testsuite>feature 2</testsuite>
</testsuite>
</testsuites>
```
in this case paratest now would fetch all testfiles from feature 1 + 2 when executing.
paratest --testsuite=all
the implementation is recursive so n-level nesting should be possible.
I will also schedule a pull request for phpunit to support this (but this take some more time...^^)
=> Nested testsuites support

src/ParaTest/Runners/PHPUnit/Options.php, test/unit/ParaTest/Runners/PHPUnit/OptionsTest.php, test/unit/ParaTest/Runners/PHPUnit/ResultPrinterTest.php
This fixes #65  (is basically a merge of that old PR).
I don't know what the old discussion was about (what diffs that discussion was about) but to me, it looks well tested.
A directory is passed in as configuration an both, phpunit.xml or phpunit.xml.dist are loaded of they exist. The only thing that could be added is a test for the load order (phpunit.xml.dist only if phpunit.xml does not exist). But I don't know what exactly @giorgiosironi was complaining about back then.
=> Merged #65: Avoid simplexml_load_file warning when config path is a directory

.scrutinizer.yml, src/ParaTest/Runners/PHPUnit/Runner.php
When uniqid is executed to fast in a row the generated id's are unique. usleep ensures a uniqueid
would be 0.12.1 i think
=> uniqid() is not unique enough so add usleep to ensure uniqueness

composer.json
=> Fix: Split autoloading into autoload and autoload-dev sections

src/ParaTest/Runners/PHPUnit/Configuration.php
I've run into troubles trying to use paratest. For security reasons some hosters disable function simplexml_load_file, but our team went even further and just compiled php without it. So what do you think about this small change?
=> avoid using simplexml_load_file for security reason

test/functional/SkippedOrIncompleteTest.php
fix https://github.com/brianium/paratest/issues/178
Use a regex to capture the output instead of just counting the number of S
=> FIX: SkippedOrIncompleteTest test fails if "S" in path

src/ParaTest/Runners/PHPUnit/ResultPrinter.php
Adds more detailed message other then "This means a PHPUnit process has crashed" when printing feedback. With this information it's much easier to start debugging what file might have an error.
=> Adds more detailed message when printing feedback

src/ParaTest/Logging/LogInterpreter.php, test/fixtures/results/data-provider-result.xml, test/unit/ParaTest/Logging/LogInterpreterTest.php, test/unit/ParaTest/ResultTester.php
Incorrent xml output if I use the dataProvider in tests #19
=> Incorrent xml output if I use the dataProvider in tests

src/ParaTest/Runners/PHPUnit/Worker.php
This PR fixes the following situation:
```
[development@localhost ~/P/no-spaces] (paratest) ./phpunit-parallel.sh 
Running phpunit in 10 processes with phpunit
Configuration read from /home/development/Projects/no-spaces/phpunit.xml
................................................................. 65 / 76 ( 85%)
........................
Time: 10.07 seconds, Memory: 7.75Mb
OK (89 tests, 903 assertions)
[development@localhost ~/P/no-spaces] (paratest) cd ..
[development@localhost ~/Projects] mv no-spaces/ "with spaces"
[development@localhost ~/Projects] cd with\ spaces/
[development@localhost ~/P/with spaces] (paratest) ./phpunit-parallel.sh 
Running phpunit in 10 processes with phpunit
Configuration read from /home/development/Projects/with spaces/phpunit.xml
[RuntimeException] …
```
=> Fix workers crashing when we're on a filesystem path with spaces

.travis.yml, composer.json, phpunit.xml.dist, src/ParaTest/Console/Commands/ParaTestCommand.php, test/functional/PHPUnitTest.php, test/functional/ParaTest/Runners/PHPUnit/RunnerIntegrationTest.php, test/functional/WrapperRunnerTest.php, test/unit/ParaTest/Console/Commands/ParaTestCommandTest.php, test/unit/ParaTest/Coverage/CoverageMergerTest.php
This adds fixes to support php 7 and phpunit 5. ( fixes #189 and #162 )
It is mainly build-/test-related:
* with php 7, phpunit catches fatal errors like normal errors => no special failure handling neccessary, they are skipped with
```PHP
if (PHP_VERSION_ID >= 70000) {
$this->markTestSkipped('fatals are handled like normal exceptions with php7');
}
```
* phpunit 5 requires a whitelist to be defined when tracking coverage
the fix for this adds a deep dependency to phpunit, because paratest can only support the ```--whitelist``` option, when phpunit does, and it does only for versions >=5.0.0
```PHP
public static function isWhitelistSupported() {
return Comparator::greaterThanOrEqualTo(\PHPUnit_Runner_Version::id(), '5.0.0');
}
```
So I need some feedback here, especially from @brianium …
=> PHP 7 & PHPUnit 5

README.md
The max batch size parameter was written `--batch-max-size` when it should actually be `--max-batch-size`.
=> Correct README parameter name --max-batch-size

composer.json, test/bootstrap.php, test/functional/FunctionalTestBase.php, test/functional/PHPUnitTest.php, test/functional/PHPUnitWarningsTest.php, test/unit/ParaTest/Coverage/CoverageMergerTest.php
As described below in comments, PHPUnit 5.1+ changed the way test warnings are treated in test suites. This is not to be confused with E_WARNINGS that are raised during tests. These are things like "test method is marked as private" or "non-existent data provider specified". In PHPUnit 4.8 these were printed as warnings in the test output, and they also caused a failed build (exit code > 0). In PHPUnit 5.1+ these still output warnings, but they do NOT output a failed exit code.
This PR adds a PHPUnit version check to change the assertion based on what we actually expect to happen.
=> Change unit test assertion depending on the version of PHPUnit being used

composer.json, test/unit/ParaTest/Runners/PHPUnit/ResultPrinterTest.php
This should allow for differences in environments/versions which check the memory usage output string. Sometimes its X.XXMB and other times it's X.XXMb.
Paratest depends directly on PHP_CodeCoverage via its code, however it does not explicity require it in composer.json. Instead it relies on the inclusion through phpunit. A recent version of phpunit completely changed the class structure of PHP CodeCoverage, so for now I simply did `composer require "phpunit/php-code-coverage:3.*"` to fix this. This [automatically] locks the project to [a maximum of] PHPUnit 5.3.5 which is the last version that supported this.
=> Fix failed build (Mb/MB check and require php-code-coverage 3.X)

src/ParaTest/Console/Testers/PHPUnit.php, test/functional/PHPUnitTest.php
When I run paratest on two projects at the same time I run into problems because the temporary file with coverage data has a static name. This PR makes the name dynamic leveraging `tempnam()`.
=> allow multiple instances of paratest running at the same time

src/ParaTest/Console/Testers/PHPUnit.php, src/ParaTest/Parser/Parser.php, test/fixtures/failing-tests/AnonymousClass.inc, test/unit/ParaTest/Parser/ParserTest/GetClassTest.php
Since php7's anonymous class names contain null bytes, we've encountered some issues with paratests' Parser-class.
This fix remove said null byte, to avoid obscure failures.
=> Fixes #202 Remove null byte from anonymous class reflection name

src/ParaTest/Logging/JUnit/TestCase.php, src/ParaTest/Logging/JUnit/Writer.php, test/fixtures/results/junit-example-result.xml, test/unit/ParaTest/Logging/JUnit/WriterTest.php
Fixes issue https://github.com/brianium/paratest/issues/199, where the paratest xml writer was allowing empty line numbers, e.g. `line=""`. This is probably due to PHP's loose typing, an empty value could be written as blank instead of `0` which is what we want.
I've written a unit test that uses a fixture xml with some `line=""` instances, and confirms that after writing the output, there is no `line=""` and there is at least one `line="0"` to confirm it changed properly.
The actual code fix is simply to check for an empty string at constructor time, and sets it to `0` if so.
This was created at Digital Ocean's Hacktoberfest in NYC.  (https://hacktoberfest.digitalocean.com/)
=> Fix issue 199, prevent empty line attributes in XML

composer.json, test/functional/PHPUnitTest.php
**1.** Trying to get this repo back in line. I think it's time to require phpunit 5.0+ (while not yet using PHPUnit 6.0 due to the namespace changes). I think this means dropping support for 5.3 as well. Composer.json has been updated.
**2.** The [testRunWithFatalParseErrorsHasExitCode255](https://travis-ci.org/brianium/paratest/jobs/172151038) test was failing on PHP 7.0 due to some change in either PHP itself, or some dependency that has changed. What it comes down to I think is that PHP 7.0 changed some fatals to exceptions, and symfony console made some changes accordingly to reflect this (?). `1` is still a "bad" exit code so it should be fine to check for either 255 or 1... but open to hearing opinions.
=> Fix Failing Build (Expected Exit Code)

src/ParaTest/Logging/JUnit/Reader.php, src/ParaTest/Parser/Parser.php, src/ParaTest/Runners/PHPUnit/ResultPrinter.php, test/unit/ParaTest/Logging/JUnit/ReaderTest.php, test/unit/ParaTest/Runners/PHPUnit/ResultPrinterTest.php
This fixes #164 and #146 
There are several bugfix proposals, none of them has been accepted so far. This approach is different and allows empty result files to be accepted, no matter what. Seems to be fine, according to tests. In case an empty result is processed, zero and empty values are accumulated, so results should not be affected. Overall count of suites is increased, but this is true, even if no tests are executed from these suites.
Please feel free to leave comments.
=> Allows groups to be specified, even if test suites do not contain tests for them

test/functional/PHPUnitTest.php
On many versions of OS X (including 10.12.1) there are inconsistencies between the temp directory returned by `sys_get_temp_dir()` and the one used by `tempnam()`.
`sys_get_temp_dir()` will return something like:
`/var/folders/0s/rlfsn9993r78qq7qjkr42x2w00058k/T`
`tempname()` will prefix with `/private` as the return value of `sys_get_temp_dir()` may not be writable:
`/private/var/folders/0s/rlfsn9993r78qq7qjkr42x2w00058k/T/paratest_oiqMU3`
This updates the test to take the directory that is returned by `tempnam()`, allowing tests to pass on OSX.
=> Fix temp dir inconsistency on os x

.travis.yml
Seen in travis output:
> HHVM is no longer supported on Ubuntu Precise.
> Please consider using Trusty with `dist: trusty`.
=> Switch to ubuntu `trusty` beta, to continue hhvm CI support in ~0.14 releases

src/ParaTest/Parser/Parser.php, test/fixtures/failing-tests/AnonymousClass.inc, test/fixtures/special-classes/NameDoesNotMatch.php, test/fixtures/special-classes/SomeNamespace/ParserTestClass.php
PHPUnit can properly handle this case without crashing.
Paratest should as well.
Before, Paratest would assume that the first class in the for loop was a
TestCase instance, and sometimes fail.
In several files in a project I work on,
there are helper classes alongside the test file,
used only in that test file.
Update test cases to reflect the new behaviour, require them to be
subclasses of PHPUnit_Framework_TestClass
- Keep giving priority to classes following PSR-0 naming
=> Allow multiple classes in one phpunit test file.

test/TestBase.php
As ParaTest now only supports PHP >= 7.0, can safely use the splat operator instead of `func_get_args()`. The feature was introduced in PHP 5.6.
See: <https://secure.php.net/manual/en/migration56.new-features.php#migration56.new-features.splat>
=> Prefer splat operator over func_get_args()

src/Console/Testers/PHPUnit.php, src/Logging/JUnit/TestCase.php, src/Logging/JUnit/TestSuite.php, src/Runners/PHPUnit/Options.php, src/Runners/PHPUnit/SuiteLoader.php, src/Runners/PHPUnit/Worker.php
- Add missing properties that were intended to be read-only
`empty($options->filter)` was called, so added a definition of the
magic method __isset() as well. (`empty($x->a)` is equivalent to `!isset($x->a) || !$x->a`)
- Fix inconsistencies between phpdoc and actual code.
- Add scalar type hints in phpdoc/real code
- Be specific about types parsed from phpunit xml output.
- stream_set_blocking expects bool, not int (Would be noticeable in strict mode)
=> fix misc minor issues noticed by Phan static analyzer

bin/phpunit-wrapper, src/Runners/PHPUnit/ExecutableTest.php, src/Runners/PHPUnit/Worker.php, test/functional/ParaTestInvoker.php
Both `phpunit-wrapper` and `phpunit` rely on `#!/usr/bin/env php` hashbash to detect the php executable.
This can be not found in the `$PATH`, or a user can start paratest with a different php than the one of the path (for ex. with a command like `/my/custom/build/php vendor/bin/paratest`.
Relying on `PHP_BINARY` to execute both the script is the only solution.
I tried to make a test for this bug, but cannot find the way to disable Travis environment.
=> Rely on PHP_BINARY to get the right executable instead of ENV

.travis.yml, composer.json
Hi, I've refactored the Travis build with the following changes:
1. Dependencies are now installed on lowest or latest version; this is mandatory because if a version is allowed we need to test it
1. PHPUnit is now pinned to ^6.0.13 because there are some issues with intermediate minor versions, never tested before this PR and point 1 got emerged
1. Symfony is now pinned to ^3.0 for the same reason, Travis fails with Symfony ~2.0 but previous Travis config didn't show it
1. Code Coverage is done in one build only, on the lowest PHP Version but with the latest dependencies; an ENV variable is set to be clear on the build
1. CS Fixes are checked on an own build without tests involved; an ENV variable is set to be clear on the build
1. PHP 7.2 is now tested, but allowed to fail
1. …
=> Travis build refactored

composer.json, src/Runners/PHPUnit/ExecutableTest.php, test/functional/ParaTestInvoker.php
This may break assumptions in some projects about the way
paratest sets up environment variables.
(I think it might clear some of them, which differs from phpunit?)
Symfony 3.3 has deprecated the old behavior, which will be removed
eventually in 4.0.
(Saw this E_USER_DEPRECATED warning in a different project with a
different error_handler callback)
Symfony/console versions 3.0-3.1 don't implement inheritEnvironmentVariables
- To be consistent about environment variables, require a minimum of 3.2
- 3.0-3.1 are about to stop being supported
https://symfony.com/roadmap?version=3.1#checker
- Keep the method_exists check for now, just in case 
See https://github.com/symfony/process/blob/3.3/Process.php#L319
=> Update symfony dep to ^3.2, automatically inherit env variables

test/functional/FunctionalTestBase.php, test/functional/ParaTestInvoker.php
Move conventional and inline with PHP recommendations.
From the PHP documentation:
http://php.net/manual/en/language.namespaces.importing.php#language.namespaces.importing
> Note that for namespaced names …, the leading backslash is unnecessary
> and not recommended, as import names must be fully qualified, and are
> not processed relative to the current namespace.
=> Remove leading backslash from use statements

src/Console/ParaTestApplication.php, src/Console/VersionProvider.php, test/unit/Console/VersionProviderTest.php
ParaTest has the version number hard-encoded.
Previously when reporting the version via --version that hard-encoded
version number was presented in the output (e.g. 1.0.1).
As technically the version changes with git commit and not every git
commit is tagged and not even every tagged commit contains the appropriate
change to the hard-encoded version number within
\ParaTest\Console\ParaTestApplication::VERSION
the wrong version is reported.
This commit addresses the issue by first looking up the installed version
of the package "brianium/paratest" from within composer's installed.json
file which contains the currently installed version (based on the git tag,
see Packagist) and if not found (e.g. you have checked out the development
version in a git clone) the version number will be taken …
=> Fix version reporting in console, closes #257

.travis.yml
`nightly` now points to 7.3-dev, no need to test it now; moved to 7.2
=> Travis: nightly -> 7.2

README.md
I consider CC an info with higher priority of scrutinizer score.
=> README.md: add code-coverage badge

.php_cs.dist, composer.json, src/Runners/PHPUnit/Configuration.php, src/Runners/PHPUnit/ExecutableTest.php, test/functional/PHPUnitTest.php, test/unit/Console/VersionProviderTest.php
This PR makes paratest compatible with Symfony 4 components as well as allowing installation as a dependency alongside projects using said components.
Symfony Process: there's no easy way to compatibilize Symfony Process usage from 3.2 to 4.0 without a great deal of boilerplate. ProcessBuilder is deprecated in 3.4 and removed in 4, so Process has to be used directly. Unfortunately the method signature is different across Symfony 3 versions (3.2 requires a string as a first argument, 3.3/4 require an array).
As a tradeoff, this PR locks minimum version at 3.4 which happens to be LTS. 3.2 is currently unsupported.
=> Symfony 4 compatibility

src/Coverage/CoverageMerger.php
When xdebug is disabled, the message why paratest fails is a bit cryptic.
This PR adds a check to see if xdebug is enabled and changes the message to be more specific if it's disabled/missing.
Related to #158
=> Suggest enabling xdebug for coverage

src/Runners/PHPUnit/Options.php
This will fix the method for determining the phpunit path, when installing e.g. on windows with the composer configuration "bin-compat": "full" and running tests inside a linux docker.  
The problem was that the current sollution determines the phpunit executable file based on the existence of the ".bat"-file. This solution will determine the executable based on file existence and the systems DIRECTORY_SEPERATOR.
=> Fixed problem composer installs with bin-compat full

src/Logging/JUnit/Writer.php, test/fixtures/results/data-provider-with-special-chars.xml, test/unit/Logging/JUnit/WriterTest.php
PR #127 started escaping all HTML entities in order to produce valid JUnit XML. However, this is problematic because characters like `—` (`&mdash;`) and `…` (`&hellip;`) get escaped and produce invalid XML due to the `&` character.
Switching to `htmlspecialchars` ensures that only intended characters are escaped.
=> Fix handling of special characters in JUnit XML

src/Console/Commands/ParaTestCommand.php, src/Console/Testers/PHPUnit.php, src/Coverage/CoverageReporter.php, src/Coverage/CoverageReporterInterface.php, src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/ExecutableTest.php, test/unit/Console/Commands/ParaTestCommandTest.php
This PR makes paratest support PhpUnit's --coverage-text option.
related issue: https://github.com/paratestphp/paratest/issues/231
=> Add option coverage-text

src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/SuiteLoader.php, src/Runners/PHPUnit/WrapperRunner.php
I had an issue where I needed to overwrite the SuiteLoader for a new runner that I was created. Although it has some protected variables, most of the functions were private.
This PR is to update all of the functions to protected and to have the load function accept a loader.
=> Make SuiteLoader more extendable

test/functional/PHPUnitTest.php, test/functional/ParaTest/Runners/PHPUnit/WorkerTest.php, test/functional/SkippedOrIncompleteTest.php, test/unit/Logging/JUnit/ReaderTest.php, test/unit/Logging/JUnit/WriterTest.php, test/unit/Logging/LogInterpreterTest.php, test/unit/Parser/ParsedClassTest.php, test/unit/Parser/ParserTest/GetClassTest.php, test/unit/Runners/PHPUnit/ConfigurationTest.php, test/unit/Runners/PHPUnit/OptionsTest.php, test/unit/Runners/PHPUnit/RunnerTest.php, test/unit/Runners/PHPUnit/SuiteLoaderTest.php
Using PHPUnit dedicated assertions will give us better error messages, making easier to debug fails. For example:
```diff
-$this->assertTrue(in_array('foo', ['bar', 'baz']));
+$this->assertContains('foo', ['baz', 'bar']);
```
Will give us:
```diff
-Failed asserting that false is true.
+Failed asserting that an array contains 'foo'.
```
=> Use dedicated PHPUnit assertions

test/unit/Console/VersionProviderTest.php
fixes #320 - version tag 2.0 broke the pattern, thrid component is now optional
=> #320 fixed - tag name 2.0 didn't match the regex pattern, adjusted pattern

src/Console/Testers/PHPUnit.php, src/Logging/JUnit/Reader.php, src/Logging/LogInterpreter.php, src/Logging/MetaProvider.php, src/Parser/ParsedClass.php, src/Parser/Parser.php, src/Runners/PHPUnit/Options.php, src/Runners/PHPUnit/ResultPrinter.php, src/Runners/PHPUnit/SqliteRunner.php, src/Runners/PHPUnit/TestFileLoader.php, test/bootstrap.php, test/fixtures/dataprovider-tests/DataProviderTest.php, test/fixtures/failing-tests/UnitTestWithErrorTest.php, test/fixtures/paratest-only-tests/TestTokenTest.php, test/fixtures/passing-tests/GroupsTest.php
Together with PHPStorm and https://github.com/kalessil/phpinspectionsea, here are some improvements that we can make to Paratest, such as unnecessaries parentheses; null coalesce operator usage; in_array instead of array_search + comparison, etc
=> Small tweaks

.travis.yml, box.json.dist
To resolve #176, The Phar executable is very useful when root project has some dependency conflict with paratest, for example `symfony/console`.
This PR require Github token to work properly, You can replace APIKEY by editing files (**"Allow edits from maintainers has checked"**), It should work like following link.
https://github.com/Gasol/paratest/releases/tag/2.0.0
See also  https://docs.travis-ci.com/user/deployment/releases/#Authenticating-with-an-OAuth-token and https://github.com/travis-ci/travis-ci/issues/2457#issuecomment-47113151
=> Publish Phar executable on Release pages

src/Runners/PHPUnit/Options.php, test/unit/Runners/PHPUnit/OptionsTest.php, test/unit/Runners/PHPUnit/ResultPrinterTest.php
Makes it a bit more portable for documentation use, or scripting it (composer scripts, shell, ..).
I'm alos suggesting setting this as a default, however that is not a must here and up to what you see as best default for the project.
=> [Feature] Allow setting processes to number of CPU cores

README.md, bin/phpunit-wrapper, docs/code-coverage.md, docs/logging.md, docu/code-coverage.md, src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/Runner.php, src/Runners/PHPUnit/Worker/BaseWorker.php, src/Runners/PHPUnit/Worker/WrapperWorker.php, src/Runners/PHPUnit/WrapperRunner.php
- Adds logfile output for WrapperRunner by prefixing bin/paratest with PT_LOGGING_ENABLE='true'. 
- Adds docs for logging. 
- Cleans up README.
=> Logfiles for WrapperRunner

.gitignore
The optional caching of test results that was introduced in PHPUnit 7.3
is now enabled by default in PHPUnit 8. This creates a
.phpunit.result.cache file.
=> Add .phpunit.result.cache to gitignore

test/fixtures/warning-tests/phpunit.xml.dist, test/functional/PHPUnitWarningsTest.php
A PHPUnit bug was fixed to not fail on a warning by default. To test
failures on warnings, define this in the test fixtures XML configuration
file.
=> Fix PHPUnitWarningsTest with PHPUnit @dev

README.md, src/Console/Commands/ParaTestCommand.php, test/unit/Console/Commands/ParaTestCommandTest.php
According to README.md functional mode flag differentiates between per-testcase- and per-testmethod-parallelization. Command input option description fixed accordingly.
=> Fix functional input option description to match the documentation

bin/phpunit-wrapper
when I run paratest with enabled [Logging WrapperRunner output](https://github.com/paratestphp/paratest/blob/master/docs/logging.md), I got a strange error:
```
PHPUnit\Framework\Exception: Fatal error: Uncaught Error: Class 'PHPUnit\Util\Configuration' not found in - on line 425
Error: Class 'PHPUnit\Util\Configuration' not found in - on line 425
Call Stack:
0.0013     549496   1. {main}() -:0
```
```
phpunit/phpunit: 7.2.0
brianium/paratest: 2.2.0
PHP version: 7.1
```
In our project I just followed this documentation: [Logging WrapperRunner output](https://github.com/paratestphp/paratest/blob/master/docs/logging.md) and it always results in the described error.
When the paratest is run with WrapperRunner enabled, the phpunit constant PHPUNIT_COMPOSER_INSTALL is not set. When the code …
=> WrapperRunner: proper PHPUNIT_COMPOSER_INSTALL constant initialization

src/Runners/PHPUnit/Runner.php
Before, there was no information on which test caused the fatal error.
After this patch, the output looks like the below (tested by adding an `eval` that caused a fatal error):
```
..S............................................................  63 / 239 ( 26%)
............................................................... 126 / 241 ( 52%)
............SSSSSSSSSS.........................SS.
In Runner.php line 122:
Fatal error in /path/to/paratest/test/functional/PHPUnitTest.php:                  
Fatal error: A void function must not return a value (did you mean "return;" instead of "return   
null;"?) in /path/to/paratest/test/WhateverThePHPFileCausingTheCrashWas.php(20) : eval()'d code  
on line 1 …
```
=> Log the path of the test encountering a fatal error

src/Runners/PHPUnit/SuiteLoader.php, test/fixtures/dataprovider-tests/DataProviderTest.php, test/functional/DataProviderTest.php
Data providers aren't always arrays, they can be any iterable (using Generators is a common pattern).
=> Allow iterable data providers

.travis.yml, composer.json
PHP 7.1 will continue to receive security support until December 2019,
and some users of paratest would have apps supporting that
(including myself)
- Paratest seems to work with *both* phpunit 7 and phpunit 8
(e.g. the xml files and the format this is parsing are unchanged)
I'm assuming there aren't any 2.x backport plans.
- It doesn't seem as if paratest has started using php 7.2's new features
Fixes #389
=> Support installing paratest 3.x with php 7.1

src/Console/Commands/ParaTestCommand.php, src/Coverage/CoverageMerger.php, src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/Options.php, test/unit/Console/Commands/ParaTestCommandTest.php, test/unit/Coverage/CoverageMergerTest.php
* Add limit for the tests recorded in coverage reports, as  these can grow massive if you have many tests which follow common code paths.
* Keeping these limited ensures merging coverage is efficient.
=> Add limit for tests recorded in coverage report

src/Console/VersionProvider.php, src/Runners/PHPUnit/ExecutableTest.php, test/functional/ParaTestInvoker.php
This fixes the error:
>"Passing a command as a string when creating a "Symfony\Component\Process\Process" instance is deprecated since Symfony 4.2, pass it as an array of its arguments instead, or use the "Process::fromShellCommandline()" constructor
=> Fixed Symfony 4 deprecated Process constructor

.gitignore, src/Logging/JUnit/TestCase.php, test/Unit/Logging/JUnit/ReaderTest.php, test/fixtures/results/multiple-errors-with-system-out.xml
Added handling of phpunit xml output with multiple errors in single testcase.
```xml
<testsuites>
<testsuite name="timeoutTest" file="/project/test/timeoutTest.php" tests="1" assertions="0" errors="2" warnings="0" failures="0" skipped="0" time="1.014721">
<testcase name="testTimeoutNotice" class="timeoutTest" classname="timeoutTest" file="/project/test/timeoutTest.php" line="8" assertions="0" time="1.014721">
<error type="PHPUnit\Framework\RiskyTestError">Risky Test
/project/vendor/phpunit/phpunit/src/TextUI/Command.php:200
/project/vendor/phpunit/phpunit/src/TextUI/Command.php:159
</error>
<error type="PHPUnit\Framework\RiskyTestError">Risky Test
/project/vendor/phpunit/phpunit/src/TextUI/Command.php:200
/project/vendor/phpunit/phpunit/src/TextUI/Command.php:159
</error> …
```
=> Support multiple TestCase error reports with system out

src/Runners/PHPUnit/ExecutableTest.php
Fixes #417
symfony/process 4.4 is still installed in phpunit 8, because
sebastian/diff only supports symfony/process 4 at the newest.
=> Don't call inheritEnvironmentVariables if it's deprecated

composer.json
paratest stopped using it in 7689cde4460bb45162319abd4f1e48ec35c2a3a2
Previously, anything using paratest as a dev dependency would have
composer/semver unexpectedly held back to `~1.2`.
https://github.com/composer/semver/releases includes 1.5.1 and 2.0.
=> Remove unused dependency on composer/semver

test/Functional/PHPUnitTest.php, test/fixtures/github/68/Issue68Test.php, test/fixtures/github/68/bootstrap68.php, test/fixtures/github/68/phpunit68.xml
=> Prove #68 is fixed

phpunit.xml.dist, src/Coverage/CoverageReporter.php, src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/Options.php, test/TestBase.php, test/Unit/Coverage/CoverageReporterTest.php, test/Unit/Runners/PHPUnit/BaseRunnerTest.php, test/Unit/Runners/PHPUnit/OptionsTest.php, test/Unit/Runners/PHPUnit/ResultPrinterTest.php, test/Unit/Runners/PHPUnit/RunnerTestCase.php, test/fixtures/phpunit-fully-configured.xml
Close #442 
Close #344 
Close #72
=> Enable coverage from XML configuration file

.gitattributes, .github/workflows/integrate.yaml, .gitignore, Makefile, README.md, composer.json, infection.json.dist, phpunit.xml.dist
=> Add mutation testing

bin/phpunit-wrapper.php, test/Unit/Runners/PHPUnit/WrapperRunnerTest.php, test/fixtures/phpunit-parallel-suite-with-globals.xml
phpunit-wrapper has a problem
it's broken in WrapperRunner
phpunit reset global variables between runs
https://phpunit.readthedocs.io/en/9.3/fixtures.html#global-state
I've got problems with global state in phpunit and this fix helped me.
I tried to user WrapperRunner in my big project, and this helps
this fix prevent variables in phpwrapper (they all in global scope) from turning to null 
(Also I removed assert here like in #539, I need this for passing all tests)
=> Fix phpunit-wrapper from resetting variables in global scope in WrapperRunner

README.md
See https://github.com/paratestphp/paratest/issues/568
=> readme: mention caveat of sharing constants between test classes

.github/workflows/integrate.yaml, phpstan-baseline.neon, src/Runners/PHPUnit/Options.php, test/Unit/Runners/PHPUnit/OptionsTest.php
This PR makes possible to use a `--no-coverage` option which make paratest ignore coverage configuration.
It is useful to ignore coverage configuration defined in xml configuration, for example if there are no coverage driver available.
=> Add support for no-coverage option

phpstan-baseline.neon, src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/Options.php, test/TestBase.php, test/Unit/Runners/PHPUnit/BaseRunnerTest.php, test/Unit/Runners/PHPUnit/OptionsTest.php
Just like for PHPUnit, you may want to store the "coverage text" to a file.
=> Add support to write coverage text to file

src/Runners/PHPUnit/SuiteLoader.php, test/Unit/Runners/PHPUnit/SuiteLoaderTest.php, test/fixtures/group_default/GroupDefaultTest.php, test/fixtures/group_default/GroupNonDefaultTest.php
Fixes https://github.com/paratestphp/paratest/issues/622
=> Ungrouped tests should have `default` group assigned

src/Coverage/CoverageReporter.php, test/Unit/Coverage/CoverageReporterTest.php, test/fixtures/phpunit-coverage-text-show-only-summary.xml
This resolves #385
`showOnlySummary` was changed to `false` in `test/fixtures/phpunit-fully-configured.xml`, as the other tests rely on the whole text coverage report being created.
I created `test/fixtures/phpunit-coverage-text-show-only-summary.xml`, which only differs from `test/fixtures/phpunit-fully-configured.xml` in part of the option `showOnlySummary` being set to `true`.
For being able to use the dataProvider `generateTextProvider` it was neccessary to overwrite the default configuration in `test/Unit/Coverage/CoverageReporterTest.php`. Therefore I extracted a method `createCoverageReporter` which takes a fixture path as an argument (to reduce code redundancy). This function is called in `setup`, as well as in the test method `testGenerateText`.
With `showOnlySummary` set to …
=> Respect configuration options of text coverage

src/Coverage/CoverageReporter.php, src/Runners/PHPUnit/BaseRunner.php, test/Unit/Coverage/CoverageReporterTest.php
Hello,
Please review the fix for displaying colors on the code coverage regarding issue #293 
This PR will display colored output, when `--colors` option is present.
Before this change, the output for  `--coverage-text --colors` had no colors.
=> Fix propsal for issue #293: Display colors on code coverage
