src/ParaTest/Runners/PHPUnit/Worker.php, test/functional/ParaTest/Runners/PHPUnit/WorkerTest.php
=> stability fix for failing phpunit runs

README.md
Just a minor addition. I thought it would be cool to showcase installs.
=> add packagist shield

src/ParaTest/Console/Testers/PHPUnit.php, src/ParaTest/Console/Testers/Tester.php, src/ParaTest/Logging/JUnit/Reader.php, src/ParaTest/Logging/JUnit/TestCase.php, src/ParaTest/Logging/JUnit/TestSuite.php, src/ParaTest/Logging/JUnit/Writer.php, src/ParaTest/Logging/LogInterpreter.php, src/ParaTest/Logging/MetaProvider.php, src/ParaTest/Parser/ParsedClass.php, src/ParaTest/Parser/ParsedObject.php, src/ParaTest/Parser/Parser.php, src/ParaTest/Runners/PHPUnit/BaseRunner.php, src/ParaTest/Runners/PHPUnit/Configuration.php, src/ParaTest/Runners/PHPUnit/ExecutableTest.php, src/ParaTest/Runners/PHPUnit/Options.php, src/ParaTest/Runners/PHPUnit/ResultPrinter.php, src/ParaTest/Runners/PHPUnit/Runner.php, src/ParaTest/Runners/PHPUnit/SuiteLoader.php, src/ParaTest/Runners/PHPUnit/SuitePath.php, src/ParaTest/Runners/PHPUnit/Worker.php, src/ParaTest/Runners/PHPUnit/WrapperRunner.php
Address code style violations reported by scrutinizer, mostly bringing code style in line with PSR-2
=> fix code style violations

src/ParaTest/Console/Testers/PHPUnit.php
This PR addresses some of the complexity in the PHPUnit Tester by extracting methods focused on specific concerns.
Fixes #149
=> extract methods from PHPUnit::getRunnerOptions

src/ParaTest/Runners/PHPUnit/Runner.php, src/ParaTest/Runners/PHPUnit/Worker.php, src/ParaTest/Runners/PHPUnit/WrapperRunner.php, test/fixtures/paratest-only-tests/EnvironmentTest.php, test/unit/ParaTest/Runners/PHPUnit/RunnerTest.php
Fix for comment discussion in https://github.com/brianium/paratest/commit/ec7216b9cdbefa0d6c358913152d33117f01c23e
=> Add seperat env for unique token

.travis.yml
=> Enhancement: Enable caching of dependencies installed with Composer

src/ParaTest/Console/ParaTestApplication.php
it's confusing thinking your dependencies are correct yet seeing a different version number
=> Bump version

src/Logging/JUnit/Reader.php, src/Logging/JUnit/TestCase.php, src/Logging/LogInterpreter.php, src/Runners/PHPUnit/Configuration.php
foreach() is faster and more readable
=> For Issue #239 : Stop using each(), it's deprecated in php 7.2

composer.json
to prevent accidentially new found issues while updating other code
=> locked php-cs-fixer to 2.3.2

README.md
=> Fix installation highlighting

src/Runners/PHPUnit/Runner.php
=> Make TEST_TOKEN indices consistent.

README.md
Build status badge shows status unknown.
=> Fix travis url

.travis.yml, composer.json, src/Runners/PHPUnit/ResultPrinter.php, test/unit/Coverage/CoverageMergerTest.php
Breaks BC with phpunit 6 (paratest needs new major version)
=> Make compatible with phpunit 7

README.md, src/Console/Commands/ParaTestCommand.php, src/Console/Testers/PHPUnit.php, src/Coverage/CoverageReporter.php, src/Coverage/CoverageReporterInterface.php, src/Runners/PHPUnit/BaseRunner.php, test/unit/Console/Commands/ParaTestCommandTest.php
Add missing PHPUnit XML coverage format required by tools like [Infection](https://github.com/infection/infection)
=> Add support for PHPUnit XML coverage

phpunit.xml.dist, src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/Configuration.php, test/unit/Runners/PHPUnit/ConfigurationTest.php
This pull request try to fix #103. I have tested in my personal project and it works. However, I'm not sure it is eventually fixed or not.
=> support phpunit setting environment variables

src/Runners/PHPUnit/Options.php, test/bootstrap.php
before:
used the composer shell script to run phpunit
now:
uses the phpunit php start script to run phpunit
=> #324 fixed - derivation of phpunit runner pointing to php instead of binary

.travis.yml
Unfortunately, the deploy section was missing in PR #322 , thus this PR.
=> Add deploy section to .travis.yml.

phpunit.xml.dist, src/Console/Commands/ParaTestCommand.php, src/Runners/PHPUnit/Configuration.php, src/Runners/PHPUnit/FullSuite.php, src/Runners/PHPUnit/Options.php, src/Runners/PHPUnit/SuiteLoader.php, src/Runners/PHPUnit/TestFileLoader.php, test/unit/Console/Commands/ParaTestCommandTest.php
cherry-pick and squash of https://github.com/ThomasDelteil/paratest/tree/parallel-suites
As detailed in https://github.com/paratestphp/paratest/issues/179
Specifically, the commits in question are: 
* https://github.com/ThomasDelteil/paratest/commit/34c2eb1f91bc34102cca742a53db03db433aeb9b
* https://github.com/ThomasDelteil/paratest/commit/b03841a6bee8543485d10fa832233ea4751ed640
=> parallel suites

README.md, docs/code-coverage.md, docu/code-coverage.md, src/Runners/PHPUnit/Runner.php
See [docs/code-coverage.md](docs/code-coverage.md)
=> Add docs for code coverage generation

src/Console/Testers/PHPUnit.php, src/Console/VersionProvider.php, src/Coverage/CoverageMerger.php, src/Logging/JUnit/Reader.php, src/Logging/JUnit/TestCase.php, src/Logging/JUnit/Writer.php, src/Logging/LogInterpreter.php, src/Logging/MetaProvider.php, src/Parser/ParsedClass.php, src/Parser/ParsedObject.php, src/Parser/Parser.php, src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/Configuration.php, src/Runners/PHPUnit/ExecutableTest.php, src/Runners/PHPUnit/FullSuite.php, src/Runners/PHPUnit/Options.php, src/Runners/PHPUnit/ResultPrinter.php, src/Runners/PHPUnit/Runner.php, src/Runners/PHPUnit/SqliteRunner.php, src/Runners/PHPUnit/SuiteLoader.php, src/Runners/PHPUnit/SuitePath.php, src/Runners/PHPUnit/TestFileLoader.php, src/Runners/PHPUnit/TestMethod.php, src/Runners/PHPUnit/Worker/BaseWorker.php, src/Runners/PHPUnit/Worker/WrapperWorker.php, src/Runners/PHPUnit/WrapperRunner.php, src/Util/Str.php
Reproduce with:
php php-cs-fixer --rules=native_function_invocation fix src --allow-risky=yes
(php-cs-fixer from : https://cs.symfony.com/)
Details:
https://veewee.github.io/blog/optimizing-php-performance-by-fq-function-calls/
=> Automated native_function_invocation fixes

.travis.yml, composer.json, test/Functional/Coverage/CoverageMergerTest.php, test/TestBase.php
This update will be effective when this pull request is validated : 
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4608
=> update of components to symfony 5

composer.json, src/Runners/PHPUnit/ExecutableTest.php, src/Runners/PHPUnit/Suite.php, src/Runners/PHPUnit/SuiteLoader.php, test/Functional/SqliteRunnerTest.php, test/Functional/WrapperRunnerTest.php, test/Unit/Runners/PHPUnit/ExecutableTestTest.php, test/fixtures/special-classes/MultiLineClassDeclarationWithDifferentFilenameThanClassnameTest.php
See:
1. https://github.com/sebastianbergmann/phpunit/blob/9.0.0/ChangeLog-9.0.md
1. https://github.com/paratestphp/paratest/pull/74
1. https://github.com/paratestphp/paratest/pull/241
=> Add PHPUnit 9 support

phpunit.xml.dist, src/Runners/PHPUnit/BaseRunner.php, test/Unit/Runners/PHPUnit/ConfigurationTest.php
Would like to use your repo in one of our projects.
The only thing is that setting environment variables outside runner itself during CI is important for us.
Might help others with similar setup as well.
=> Do not overwrite existing env variables

.gitignore, src/Runners/PHPUnit/ResultPrinter.php, test/Unit/Runners/PHPUnit/ResultPrinterTest.php
Added feedback item colours similar to what phpunit does
Fixed broken test and PHPUnit 9 deprecation asserts
=> Add feedback item colours

.travis.yml, test/fixtures/passing-tests/LegacyNamespaceTest.php
Closes https://github.com/paratestphp/paratest/issues/446
=> Fix build and add PHP 7.4 to Travis

.travis.yml, composer.json, src/Runners/PHPUnit/ResultPrinter.php, test/Functional/Coverage/CoverageMergerTest.php, test/Functional/Coverage/CoverageReporterTest.php, test/Functional/DataProviderTest.php, test/Functional/FunctionalTestBase.php, test/Functional/GroupTest.php, test/Functional/OutputTest.php, test/Functional/PHPUnitTest.php, test/Unit/Console/VersionProviderTest.php, test/Unit/Logging/JUnit/ReaderTest.php, test/Unit/Runners/PHPUnit/ExecutableTestTest.php, test/Unit/Runners/PHPUnit/ResultPrinterTest.php
Addresses part of #450 and should be enough for a `4.1.0` release.
=> Support latest PHPUnit only

.github/workflows/integrate.yaml
PCOV and SQLite are needed in order to run the full test suite
=> [GA] Tests: run with PCOV and SQLite

.github/workflows/integrate.yaml, composer-require-checker.json, composer.json
Tools available since https://github.com/shivammathur/setup-php/releases/tag/2.4.0
=> Lint composer.json file

.github/workflows/integrate.yaml, src/Console/VersionProvider.php, test/Unit/Console/VersionProviderTest.php
=> Remove version gathered from git as it's used only within the test suite

src/Runners/PHPUnit/Worker/BaseWorker.php, test/Functional/FunctionalTestBase.php, test/Functional/PHPUnitTest.php, test/Functional/ParaTestInvoker.php
=> Escape PHP_BINARY as well

test/Functional/FunctionalTestBase.php, test/Functional/ParaTestInvoker.php, test/Functional/WrapperRunnerTest.php, test/fixtures/parallel-suite/One/FourTest.php, test/fixtures/parallel-suite/One/OneTest.php, test/fixtures/parallel-suite/One/ThreeTest.php, test/fixtures/parallel-suite/One/TwoTest.php, test/fixtures/parallel-suite/ParallelBase.php, test/fixtures/parallel-suite/Two/FourTest.php, test/fixtures/parallel-suite/Two/OneTest.php, test/fixtures/parallel-suite/Two/ThreeTest.php, test/fixtures/parallel-suite/Two/TwoTest.php, test/fixtures/phpunit-parallel-suite.xml
See:
1. https://github.com/paratestphp/paratest/pull/349
1. https://github.com/paratestphp/paratest/pull/351
1. https://github.com/paratestphp/paratest/issues/179
=> Add test for --parallel-suite option

src/Runners/PHPUnit/SuiteLoader.php, test/Functional/FunctionalTestBase.php, test/Functional/PHPUnitTest.php, test/fixtures/github/432/Issue432BarTest.php, test/fixtures/github/432/Issue432FooTest.php, test/fixtures/github/432/phpunit432.xml
=> Use native PHPUnit annotation helpers

.github/lint-xml-configuration/lint-xml-configuration.sh, README.md, composer.json, phpstan.neon.dist, phpunit.xml.dist, psalm.xml.dist, src/Coverage/CoverageMerger.php, src/Runners/PHPUnit/Options.php, src/Runners/PHPUnit/Worker/BaseWorker.php, test/Functional/Coverage/CoverageReporterTest.php, test/Unit/Coverage/CoverageMergerTest.php, test/fixtures/coverage-tests/result_printer_test-windows.cov, test/fixtures/coverage-tests/result_printer_test.cov, test/fixtures/coverage-tests/runner_test-windows.cov, test/fixtures/coverage-tests/runner_test.cov
=> Allow PHPUnit 9.3

bin/phpunit-sqlite-wrapper.php, bin/phpunit-wrapper.php, phpstan.neon.dist, src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/ExecutableTest.php, src/Runners/PHPUnit/Options.php, src/Runners/PHPUnit/Worker/BaseWorker.php, src/Runners/PHPUnit/Worker/SqliteWorker.php, src/Runners/PHPUnit/Worker/WrapperWorker.php, src/Runners/PHPUnit/WrapperRunner.php, test/Unit/Runners/PHPUnit/OptionsTest.php, test/Unit/Runners/PHPUnit/RunnerTest.php, test/Unit/Runners/PHPUnit/RunnerTestCase.php
=> Support --stop-on-failure on WrapperRunner and SqliteRunner too

src/Runners/PHPUnit/BaseRunner.php, test/Unit/Runners/PHPUnit/BaseRunnerTest.php
=> BaseRunner -> Writer $name

Makefile, test/fixtures/warning_tests/HasWarningsTest.php
See https://github.com/sebastianbergmann/phpunit/commit/155e5b0549093e2c494cc303c2910daeac0b046c
=> Make test suite compatible with PHPUnit 9.4

README.md, src/Runners/PHPUnit/ExecutableTest.php, src/Runners/PHPUnit/FullSuite.php, src/Runners/PHPUnit/Options.php, src/Runners/PHPUnit/ResultPrinter.php, src/Runners/PHPUnit/Suite.php, src/Runners/PHPUnit/SuiteLoader.php, src/Runners/PHPUnit/TestMethod.php, test/Unit/ResultTester.php, test/Unit/Runners/PHPUnit/BaseRunnerTest.php, test/Unit/Runners/PHPUnit/ExecutableTestTest.php, test/Unit/Runners/PHPUnit/FullSuiteTest.php, test/Unit/Runners/PHPUnit/OptionsTest.php, test/Unit/Runners/PHPUnit/ResultPrinterTest.php, test/Unit/Runners/PHPUnit/SuiteTest.php, test/Unit/Runners/PHPUnit/TestMethodTest.php
Supersedes https://github.com/paratestphp/paratest/pull/533
=> Add --log-teamcity option

src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/SuiteLoader.php
See https://github.com/paratestphp/paratest/pull/539#discussion_r505416835
=> Make unnecessary associative array a list

.github/workflows/integrate.yaml, composer.json, src/Runners/PHPUnit/ResultPrinter.php, test/Unit/Runners/PHPUnit/BaseRunnerTest.php
Close https://github.com/paratestphp/paratest/pull/544
=> Support TeamCity file to be a FIFO

test/Unit/Runners/PHPUnit/BaseRunnerTest.php, test/Unit/Runners/PHPUnit/RunnerTestCase.php, test/fixtures/deterministic_random/MtRandTest.php, test/fixtures/phpunit-deterministic-random.xml
Close https://github.com/paratestphp/paratest/pull/548
=> Check test randomness outcome is deterministic with --random-order-seed set

src/Runners/PHPUnit/ExecutableTest.php
https://wiki.php.net/rfc/inheritance_private_methods
https://github.com/php/php-src/blob/php-8.0.0RC3/UPGRADING#L200
=> [PHP 8] Warning: Private methods cannot be final as they are never overridden by other classes

src/Runners/PHPUnit/Worker/RunnerWorker.php, src/Runners/PHPUnit/Worker/WrapperWorker.php
=> Fix executable args for phpdbg

README.md
The previous link is not working anymore.
=> Update link to PHPUnit ChangeLog

src/Runners/PHPUnit/BaseRunner.php, src/Runners/PHPUnit/SuiteLoader.php, test/Unit/Runners/PHPUnit/RunnerTestCase.php, test/Unit/Runners/PHPUnit/SuiteLoaderTest.php
=> Zero exit code if no tests executed (fixes #636)

src/Logging/JUnit/Writer.php, test/Unit/Logging/JUnit/WriterTest.php
=> Fix #629 JUnit log, create directory if not existent

.github/workflows/integrate.yaml, composer.json, src/Runners/PHPUnit/Suite.php, test/Unit/ResultTester.php, test/Unit/Runners/PHPUnit/ResultPrinterTest.php, test/Unit/Runners/PHPUnit/SuiteTest.php
Fix https://github.com/paratestphp/paratest/issues/369
=> Correctly count test with a @depends relationship
